github.com:
    users:
        melindachang:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: melindachang
