github.com:
    users:
        melindachang:
            oauth_token: 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
    git_protocol: https
    user: melindachang
    oauth_token: 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
