# ==========================================
# LANGUAGE SETUP
# ==========================================

[[language]]
name = "bash"
auto-format = true

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args = ["--style", "Chromium"] }

[[language]]
name = "css"
auto-format = true
language-servers = ["vscode-css-languageserver", "tailwindcss-ls", "oxfmt"]

[[language]]
name = "glsl"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "html"
auto-format = true
language-servers = ["vscode-html-languageserver", "oxfmt"]

[[language]]
name = "javascript"
auto-format = true
language-servers = ["typescript-language-server", "oxfmt", "oxlint"]

[[language]]
name = "json"
auto-format = true
language-servers = ["vscode-json-languageserver", "oxfmt"]

[[language]]
name = "latex"
auto-format = true
formatter = { command = "tex-fmt", args = ["--stdin"] }

[[language]]
name = "markdown"
language-servers = ["marksman"]

[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]
file-types = ["py", "pyi", "vpy"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }

[[language]]
name = "scheme"
language-servers = ["steel-language-server"]
auto-format = true
formatter = { command = "raco", args = ["fmt", "--width", "80"] }

[[language]]
name = "scss"
auto-format = true
language-servers = ["vscode-css-languageserver", "tailwindcss-ls", "oxfmt"]

[[language]]
name = "svelte"
auto-format = true
language-servers = ["svelteserver", "tailwindcss-ls", "oxfmt", "oxlint"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["taplo"]

[[language]]
name = "tsx"
auto-format = true
language-servers = ["typescript-language-server", "oxfmt", "oxlint"]

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server", "oxfmt", "oxlint"]

[[language]]
name = "typst"
auto-format = true
formatter = { command = "typstyle" }

[[language]]
name = "vue"
auto-format = true
language-servers = ["vue-language-server", "oxfmt", "oxlint", "tailwindcss-ls"]

[[language]]
name = "yaml"
auto-format = true

# ==========================================
# LSP CONFIG
# ==========================================

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
config = { harper-ls = { diagnosticSeverity = "error", linters = { long_sentences = false } } }

[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true
executable = "latexmk"
args = [
  "-lualatex",
  "-interaction=nonstopmode",
  "-synctex=1",
  "-shell-escape",
  "%f",
]

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = ["--synctex-forward", "%l:%c:%f", "%p"]

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true

[language-server.oxfmt]
command = "oxfmt"
args = ["--lsp"]

[language-server.oxlint]
command = "oxlint"
args = ["--lsp"]

[language-server.ruff]
command = "ruff"
args = ["server"]
environment = { "RUFF_TRACE" = "messages" }

[language-server.rust-analyzer.config]
check.command = "clippy"

[language-server.steel-language-server]
command = "steel-language-server"

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
