[[language]]
name = "toml"
auto-format = true
roots = ["."]
language-servers = ["taplo"]
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.harper-ls]
args = ["--stdio"]
command = "harper-ls"
config = { harper-ls = { diagnosticSeverity = "error", linters = { long_sentences = false } } }
