matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":em1"
    replace: "melindachang.hy@gmail.com"
  - trigger: ":em2"
    replace: "melindachang.shadow@gmail.com"
  - trigger: ":em3"
    replace: "melindachang2028@u.northwestern.edu"
