-- return {
--   {
--     'MunifTanjim/nui.nvim',
--   },
--   {
--     dir = '~/src/codeberg.org/melindachang/deneote.nvim',
--     opts = {
--       default_workspace_dir = '~/notes',
--       known_keywords = { 'idea', 'fleet', 'log', 'research', 'journal', 'reading', 'lecture' },
--     },
--   },
-- }
